const fs = require("fs");
const path = require("path");

const { Font } = require("fonteditor-core");
const contours2svgModule = require("fonteditor-core/lib/ttf/util/contours2svg");
const wawoff = require("wawoff2");

const contours2svg = contours2svgModule.default || contours2svgModule;

const REPO_ROOT = path.resolve(__dirname, "..");
const EXCALIFONT_DIRECTORY = path.resolve(
  REPO_ROOT,
  "packages/excalidraw/fonts/Excalifont",
);
const OUTPUT_FILE = path.resolve(
  REPO_ROOT,
  "packages/element/src/excalifontOutlineManifest.generated.ts",
);

const SUPPORTED_CODE_POINT_RANGES = [
  [0x20, 0x7e],
  [0xa0, 0x17f],
  [0x2010, 0x2027],
  [0x2030, 0x203a],
  [0x20ac, 0x20ac],
];

const buildSupportedCodePoints = () => {
  const supportedCodePoints = [];

  for (const [start, end] of SUPPORTED_CODE_POINT_RANGES) {
    for (let codePoint = start; codePoint <= end; codePoint += 1) {
      supportedCodePoints.push(codePoint);
    }
  }

  return supportedCodePoints;
};

const loadFont = async (filePath) => {
  const woff2Buffer = await fs.promises.readFile(filePath);
  const snftBuffer = new Uint8Array(
    await wawoff.decompress(woff2Buffer),
  ).buffer;

  try {
    return Font.create(snftBuffer, {
      compound2simple: true,
      type: "ttf",
      hinting: true,
      kerning: true,
    });
  } catch {
    return Font.create(snftBuffer, {
      compound2simple: true,
      type: "otf",
      hinting: true,
      kerning: true,
    });
  }
};

const buildGlyphRecord = (glyph) => {

  if (!glyph) {
    return null;
  }

  return {
    advanceWidth: glyph.advanceWidth || 0,
    leftSideBearing: glyph.leftSideBearing || 0,
    path: glyph.contours ? contours2svg(glyph.contours, 2) : "",
    xMax: glyph.xMax || 0,
    xMin: glyph.xMin || 0,
    yMax: glyph.yMax || 0,
    yMin: glyph.yMin || 0,
  };
};

const buildGlyphsByCodePoint = (fonts) => {
  const glyphsByCodePoint = new Map();

  for (const font of fonts) {
    for (const glyph of font.data.glyf) {
      if (!glyph.unicode || !glyph.unicode.length) {
        continue;
      }

      for (const codePoint of glyph.unicode) {
        if (!glyphsByCodePoint.has(codePoint)) {
          glyphsByCodePoint.set(codePoint, glyph);
        }
      }
    }
  }

  return glyphsByCodePoint;
};

const buildManifest = (fonts) => {
  const supportedCodePoints = buildSupportedCodePoints();
  const glyphsByCodePoint = buildGlyphsByCodePoint(fonts);
  const glyphs = {};

  for (const codePoint of supportedCodePoints) {
    const glyphRecord = buildGlyphRecord(glyphsByCodePoint.get(codePoint));

    if (glyphRecord) {
      glyphs[String(codePoint)] = glyphRecord;
    }
  }

  if (!glyphs["160"] && glyphs["32"]) {
    glyphs["160"] = glyphs["32"];
  }

  const metricsSourceFont = fonts[0];

  return {
    ascender: metricsSourceFont.data.hhea.ascent,
    descender: metricsSourceFont.data.hhea.descent,
    glyphs,
    supportedCodePoints: Object.keys(glyphs)
      .map((codePoint) => Number(codePoint))
      .sort((left, right) => left - right),
    unitsPerEm: metricsSourceFont.data.head.unitsPerEm,
    version: 1,
  };
};

const formatManifestSource = (manifest) => {
  return [
    'import type { ExcalifontOutlineManifest } from "./excalifontOutlineManifest";',
    "",
    "// Generated by scripts/buildExcalifontOutlineManifest.js.",
    "export const EXCALIFONT_OUTLINE_MANIFEST: ExcalifontOutlineManifest =",
    `${JSON.stringify(manifest, null, 2)} as const;`,
    "",
  ].join("\n");
};

const main = async () => {
  const fontFileNames = (await fs.promises.readdir(EXCALIFONT_DIRECTORY))
    .filter((fileName) => fileName.endsWith(".woff2"))
    .sort();

  if (!fontFileNames.length) {
    throw new Error(`No Excalifont WOFF2 files found in ${EXCALIFONT_DIRECTORY}`);
  }

  const fonts = await Promise.all(
    fontFileNames.map((fileName) =>
      loadFont(path.resolve(EXCALIFONT_DIRECTORY, fileName)),
    ),
  );

  const manifest = buildManifest(fonts);
  const source = formatManifestSource(manifest);

  await fs.promises.writeFile(OUTPUT_FILE, source);

  console.log(
    `Wrote ${manifest.supportedCodePoints.length} Excalifont outline glyphs to ${path.relative(
      REPO_ROOT,
      OUTPUT_FILE,
    )}`,
  );
};

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});